In [85]:
import tensorflow as tf
import numpy as np
tf.InteractiveSession()

## tf.reverse

In [86]:
x = tf.constant(np.reshape(np.arange(24), (2, 3, 4)))

In [87]:
x.eval()

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [88]:
tf.reverse(x, [1]).eval()

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

## tf.stack

In [89]:
x = tf.constant([1, 4])
y = tf.constant([2, 5])
z = tf.constant([3, 6])

In [90]:
tf.stack([x, y, z], axis = 0).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [91]:
tf.stack([x, y, z], axis = 1).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [92]:
num_steps = 2
batch_size = 3
hidden_size = 10
vocab_size = 30
l =[]
x1 = tf.constant(np.reshape(np.arange(3 * 10), (3, 10)))
x2 = tf.constant(np.reshape(np.arange(30, 60), (3, 10)))
l.append(x1)
l.append(x2)
l

[<tf.Tensor 'Const_11:0' shape=(3, 10) dtype=int64>,
 <tf.Tensor 'Const_12:0' shape=(3, 10) dtype=int64>]

In [93]:
x1.eval() 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9] is the dwr of the first word of the first sentence in the batch

In [94]:
x2.eval() 

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

[30, 31, 32, 33, 34, 35, 36, 37, 38, 39] is the dwr of the second word of the first sentence in the batch

In [95]:
y = tf.stack(axis = 0, values = l)
y.eval()

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]])

In [96]:
z = tf.stack(axis = 1, values = l)
z.eval()

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]],

       [[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]])

now we have stacked the output so that each consecutive row is the hidden representation of a word

In [97]:
z = tf.cast(tf.reshape(y, [-1, hidden_size]), tf.float16)
print(z.get_shape())
print(z.eval())
print(z.eval().shape)

(6, 10)
[[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.  15.  16.  17.  18.  19.]
 [ 20.  21.  22.  23.  24.  25.  26.  27.  28.  29.]
 [ 30.  31.  32.  33.  34.  35.  36.  37.  38.  39.]
 [ 40.  41.  42.  43.  44.  45.  46.  47.  48.  49.]
 [ 50.  51.  52.  53.  54.  55.  56.  57.  58.  59.]]
(6, 10)
