In [3]:
import numpy as np

In [4]:
def softmax(x):
    """Compute the softmax function for each row of the input x.

    It is crucial that this function is optimized for speed because
    it will be used frequently in later code. You might find numpy
    functions np.exp, np.sum, np.reshape, np.max, and numpy
    broadcasting useful for this task.

    Numpy broadcasting documentation:
    http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

    You should also make sure that your code works for a single
    N-dimensional vector (treat the vector as a single row) and
    for M x N matrices. This may be useful for testing later. Also,
    make sure that the dimensions of the output match the input.

    You must implement the optimization in problem 1(a) of the
    written assignment!

    Arguments:
    x -- A N dimensional vector or M x N dimensional numpy matrix.

    Return:
    x -- You are allowed to modify x in-place
    """
    orig_shape = x.shape

    if len(x.shape) > 1:
        # Matrix
        ### YOUR CODE HERE 
        max_vals = np.expand_dims(np.max(x, axis = 1), 0).T
        x = x - max_vals
        x = np.exp(x)
        x_col_sums = np.expand_dims(np.sum(x, axis = 1), 0).T
        x = x/x_col_sums
        
        ### END YOUR CODE
    else:
        # Vector
        ### YOUR CODE HERE
        max_val = np.max(x)
        x = x - max_val
        x = np.exp(x)
        x_sum = np.sum(x)
        x = x/x_sum
        ### END YOUR CODE

    assert x.shape == orig_shape
    return x

In [6]:
softmax(np.array([0.2, 0.3, 0.1, -0.2, -0.2, 0.1, 0.7]))

array([ 0.14483922,  0.1600721 ,  0.13105595,  0.09708864,  0.09708864,
        0.13105595,  0.23879951])

In [5]:
# Create a test matrix
x = np.arange(8).reshape(2, 4).astype(np.float32)
print(x)
max_vals = np.expand_dims(np.max(x, axis = 1), 0).T
print(max_vals)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]]
[[ 3.]
 [ 7.]]


In [110]:
# Make the softmax numerically stable
x = x - max_vals
print(x)

[[-3. -2. -1.  0.]
 [-3. -2. -1.  0.]]


In [111]:
x = np.exp(x)
print(x)

[[ 0.04978707  0.13533528  0.36787945  1.        ]
 [ 0.04978707  0.13533528  0.36787945  1.        ]]


In [112]:
x_row_sums = np.expand_dims(np.sum(x, axis = 1), 0).T
print(x_row_sums)

[[ 1.55300176]
 [ 1.55300176]]


In [113]:
x/x_row_sums

array([[ 0.0320586 ,  0.08714432,  0.23688284,  0.64391428],
       [ 0.0320586 ,  0.08714432,  0.23688284,  0.64391428]], dtype=float32)

In [114]:
def test_softmax_basic():
    """
    Some simple tests to get you started.
    Warning: these are not exhaustive.
    """
    print "Running basic tests..."
    test1 = softmax(np.array([1,2]))
    print test1
    ans1 = np.array([0.26894142,  0.73105858])
    assert np.allclose(test1, ans1, rtol=1e-05, atol=1e-06)

    test2 = softmax(np.array([[1001,1002],[3,4]]))
    print test2
    ans2 = np.array([
        [0.26894142, 0.73105858],
        [0.26894142, 0.73105858]])
    assert np.allclose(test2, ans2, rtol=1e-05, atol=1e-06)

    test3 = softmax(np.array([[-1001,-1002]]))
    print test3
    ans3 = np.array([0.73105858, 0.26894142])
    assert np.allclose(test3, ans3, rtol=1e-05, atol=1e-06)

    print "You should be able to verify these results by hand!\n"

In [115]:
def test_softmax():
    """
    Use this space to test your softmax implementation by running:
        python q1_softmax.py
    This function will not be called by the autograder, nor will
    your tests be graded.
    """
    print "Running your tests..."
    ### YOUR CODE HERE
    raise NotImplementedError
    ### END YOUR CODE

In [116]:
test_softmax_basic()

Running basic tests...
[ 0.26894142  0.73105858]
[[ 0.26894142  0.73105858]
 [ 0.26894142  0.73105858]]
[[ 0.73105858  0.26894142]]
You should be able to verify these results by hand!

